name: Blue Green EKS Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: ap-south-1
  EKS_CLUSTER: hello-eks-cluster
  ECR_REPOSITORY: hello-eks-pipeline
  ECR_REGISTRY: 434655688160.dkr.ecr.ap-south-1.amazonaws.com

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build Spring Boot Application
        run: mvn clean package -DskipTests


  sonar:
    name: Sonar Analysis
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Dsonar.organization=nebasishp
          -Dsonar.projectKey=nebasishp_hello-eks-pipeline
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}


  docker-ecr:
    name: Docker Build and ECR Push
    needs: sonar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::434655688160:role/hello-eks-github-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build \
            -t $ECR_REPOSITORY:${{ github.sha }} .

      - name: Push Docker Image to ECR
        run: |
          docker tag \
            $ECR_REPOSITORY:${{ github.sha }} \
            $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}

          docker push \
            $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}


  deploy:
    name: Deploy Blue Green
    needs: docker-ecr
    runs-on: ubuntu-latest

    outputs:
      active-color: ${{ steps.colors.outputs.active }}
      new-color: ${{ steps.colors.outputs.inactive }}

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::434655688160:role/hello-eks-github-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Configure EKS
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $EKS_CLUSTER

      - name: Verify EKS Connection
        run: kubectl get nodes

      - name: Find Active and Inactive Color
        id: colors
        shell: bash
        run: |
          ACTIVE=$(kubectl get service hello-eks-service \
            -o jsonpath='{.spec.selector.version}')

          echo "Current active color = $ACTIVE"

          if [ "$ACTIVE" = "blue" ]; then
            INACTIVE="green"
          else
            INACTIVE="blue"
          fi

          echo "New version will deploy to = $INACTIVE"

          echo "active=$ACTIVE" >> "$GITHUB_OUTPUT"
          echo "inactive=$INACTIVE" >> "$GITHUB_OUTPUT"

      - name: Deploy New Version to Inactive Color
        shell: bash
        run: |
          INACTIVE="${{ steps.colors.outputs.inactive }}"

          kubectl set image \
            deployment/hello-eks-$INACTIVE \
            hello-eks-container=$ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}

      - name: Wait for New Version
        shell: bash
        run: |
          INACTIVE="${{ steps.colors.outputs.inactive }}"

          kubectl rollout status \
            deployment/hello-eks-$INACTIVE \
            --timeout=180s

      - name: Show Blue Green Pods
        run: |
          kubectl get pods \
            -l app=hello-eks \
            -o wide \
            --show-labels

      - name: Switch Traffic
        shell: bash
        run: |
          INACTIVE="${{ steps.colors.outputs.inactive }}"

          kubectl patch service hello-eks-service \
            --type merge \
            -p "{\"spec\":{\"selector\":{\"app\":\"hello-eks\",\"version\":\"$INACTIVE\"}}}"


  verify:
    name: Verify Deployment
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::434655688160:role/hello-eks-github-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Configure EKS
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $EKS_CLUSTER

      - name: Verify Active Color
        run: |
          echo "Previous color: ${{ needs.deploy.outputs.active-color }}"
          echo "New live color: ${{ needs.deploy.outputs.new-color }}"

          echo "Service currently points to:"

          kubectl get service hello-eks-service \
            -o jsonpath='{.spec.selector.version}'

          echo ""

      - name: Verify Service Endpoint
        run: |
          kubectl get endpointslices \
            -l kubernetes.io/service-name=hello-eks-service \
            -o wide

      - name: Verify Running Pods
        run: |
          kubectl get pods -l app=hello-eks -o wide

      - name: Final Deployment Status
        run: |
          echo "================================"
          echo "BLUE GREEN DEPLOYMENT COMPLETE"
          echo "================================"

          echo ""
          kubectl get deployments

          echo ""
          kubectl get svc hello-eks-service